import type { Quote } from "@/types/quote";

export const SEED_QUOTES: Quote[] = [
  {
    id: "hero-1",
    text: "Music no need permission to enter your spirit.",
    author: "Santa",
    category: "music",
    theme: "cinematic",
    alignment: "center",
    featured: true,
    likes: 284,
    createdAt: "2025-01-15T00:00:00.000Z",
  },
  {
    id: "1",
    text: "The soul becomes dyed with the color of its thoughts.",
    author: "Marcus Aurelius",
    category: "wisdom",
    theme: "dark",
    alignment: "left",
    featured: true,
    likes: 412,
    createdAt: "2025-01-10T00:00:00.000Z",
  },
  {
    id: "2",
    text: "We accept the love we think we deserve.",
    author: "Stephen Chbosky",
    category: "love",
    theme: "beige",
    alignment: "center",
    featured: true,
    likes: 891,
    createdAt: "2025-01-08T00:00:00.000Z",
  },
  {
    id: "3",
    text: "Not all those who wander are lost.",
    author: "J.R.R. Tolkien",
    category: "poetry",
    theme: "minimal",
    alignment: "center",
    likes: 567,
    createdAt: "2025-01-05T00:00:00.000Z",
  },
  {
    id: "4",
    text: "Life is what happens when you're busy making other plans.",
    author: "John Lennon",
    category: "life",
    theme: "cinematic",
    alignment: "left",
    likes: 723,
    createdAt: "2025-01-03T00:00:00.000Z",
  },
  {
    id: "5",
    text: "Where words fail, music speaks.",
    author: "Hans Christian Andersen",
    category: "music",
    theme: "dark",
    alignment: "right",
    likes: 445,
    createdAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "6",
    text: "In the middle of difficulty lies opportunity.",
    author: "Albert Einstein",
    category: "wisdom",
    theme: "minimal",
    alignment: "center",
    likes: 334,
    createdAt: "2024-12-28T00:00:00.000Z",
  },
];

export const CATEGORY_LABELS: Record<
  Exclude<import("@/types/quote").QuoteCategory, "all">,
  string
> = {
  music: "Music",
  love: "Love",
  life: "Life",
  wisdom: "Wisdom",
  poetry: "Poetry",
};
